import { Convergence, Marck_Script, Imprima, Livvic } from "next/font/google";
import "./globals.css";
import "./reset.css";

const convergence = Convergence({
  subsets: ["latin"],
  variable: "--font-convergence",
  weight: ["400"],
});
const marck = Marck_Script({
  subsets: ["latin"],
  variable: "--font-marck",
  weight: ["400"],
});
const imprima = Imprima({
  subsets: ["latin"],
  variable: "--font-imprima",
  weight: ["400"],
});
const livvic = Livvic({
  subsets: ["latin"],
  variable: "--font-livvic",
  weight: ["700"],
});

export const metadata = {
  title: "Pocket Dictionary",
  description: "Generated by create english app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${convergence.variable} ${marck.variable} ${imprima.variable} ${livvic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
